apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listner-push
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "eventTypes"
            value: ["push"]    
      bindings:
        - ref: tekton-trigger-binding-push
      template:
          ref: tekton-trigger-template-push
    - name: github-listener-pull
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "eventTypes"
            value: ["pull_request"]
      bindings:
        - ref: tekton-trigger-binding-pull
      template:
          ref: tekton-trigger-template-pull