apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tekton-trigger-binding
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: tag-name
    value: $(body.repository.default_branch)
  - name: image-full-path-with-tag
    value: quay.io/rh-ee-ksaha/test:latest
  - name: deployment-manifest
    value: https://raw.githubusercontent.com/koustavsaha/spring-boot-docker/master/TektonPipelines/Resources/deployment.yaml