apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tekton-trigger-binding-push
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: tag-name
    value: $(body.head_commit.id)
  - name: image-full-path-with-tag
    value: quay.io/rh-ee-ksaha/test:ProductionBy$(body.head_commit.id)
