apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tekton-trigger-binding-pull
spec:
  params:
  - name: repo-url
    value: $(body.repository.html_url)
  - name: tag-name
    value: $(body.pull_request.head.sha)
  - name: image-full-path-with-tag
    value: quay.io/rh-ee-ksaha/test:PRby$(body.pull_request.head.sha)

