apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-git-clone-build-push-deploy-
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-push
  params:
  - name: repo-url
    value: https://github.com/koustavsaha/spring-boot-docker/
  - name: tag-name
    value: master
  - name: image-full-path-with-tag
    value: quay.io/rh-ee-ksaha/test:latest
  workspaces:
  - name: maven-settings
    configmap:
      name: maven-settings
  - name: workspace
    persistentvolumeclaim:
      claimName: shared-workspac
  - name: quay-cred
    secret:
      secretName: quay-secret
  - name: empty-dir
    emptyDir: {}
